// Copy electron entry files into the CRA build folder so electron-builder's react-cra preset (which sets main to build/electron.js)
// points to a real file at runtime.

const fs = require('fs');
const path = require('path');

const root = process.cwd();
const srcElectron = path.join(root, 'public', 'electron.js');
const srcPreload = path.join(root, 'public', 'preload.js');
const srcSplash = path.join(root, 'public', 'splash.html');
const srcIcon = path.join(root, 'public', 'assets', 'img', 'logo_dark.png');
const outDir = path.join(root, 'build');
const outElectron = path.join(outDir, 'electron.js');
const outPreload = path.join(outDir, 'preload.js');
const outSplash = path.join(outDir, 'splash.html');
const outIcon = path.join(outDir, 'icon.png');
const outIconIco = path.join(outDir, 'icon.ico');

function copyFile(src, dest) {
  if (!fs.existsSync(src)) {
    console.error(`[postbuild] Missing source: ${src}`);
    process.exit(1);
  }
  fs.copyFileSync(src, dest);
  console.log(`[postbuild] Copied ${path.relative(root, src)} -> ${path.relative(root, dest)}`);
}

if (!fs.existsSync(outDir)) {
  console.error(`[postbuild] Missing build dir: ${outDir}`);
  process.exit(1);
}

copyFile(srcElectron, outElectron);
copyFile(srcPreload, outPreload);
copyFile(srcSplash, outSplash);
copyFile(srcIcon, outIcon);

// Copy PNG as ICO (Windows will use PNG as ICO, but we'll also create a proper reference)
// Electron-builder will generate icon.ico from icon.png automatically, but we ensure the path is correct
try {
  // If icon.ico doesn't exist, electron-builder will create it from icon.png
  // For now, just ensure icon.png is in place
  console.log(`[postbuild] Icon copied - electron-builder will generate icon.ico from icon.png during build`);
} catch (e) {
  console.warn(`[postbuild] Note: icon.ico will be generated by electron-builder`);
}
