// Copy electron entry files into the CRA build folder so electron-builder's react-cra preset (which sets main to build/electron.js)
// points to a real file at runtime.

const fs = require('fs');
const path = require('path');

const root = process.cwd();
const srcElectron = path.join(root, 'public', 'electron.js');
const srcPreload = path.join(root, 'public', 'preload.js');
const srcSplash = path.join(root, 'public', 'splash.html');
const srcIcon = path.join(root, 'public', 'assets', 'img', 'logo_dark.png');
const outDir = path.join(root, 'build');
const outElectron = path.join(outDir, 'electron.js');
const outPreload = path.join(outDir, 'preload.js');
const outSplash = path.join(outDir, 'splash.html');
const outIcon = path.join(outDir, 'icon.png');

function copyFile(src, dest) {
  if (!fs.existsSync(src)) {
    console.error(`[postbuild] Missing source: ${src}`);
    process.exit(1);
  }
  fs.copyFileSync(src, dest);
  console.log(`[postbuild] Copied ${path.relative(root, src)} -> ${path.relative(root, dest)}`);
}

if (!fs.existsSync(outDir)) {
  console.error(`[postbuild] Missing build dir: ${outDir}`);
  process.exit(1);
}

copyFile(srcElectron, outElectron);
copyFile(srcPreload, outPreload);
copyFile(srcSplash, outSplash);
copyFile(srcIcon, outIcon);

// Note: icon.ico will be generated by electron-builder from icon.png
// If you need a custom .ico file, you can create it manually or use a tool like sharp
console.log(`[postbuild] Icon copied - electron-builder will generate .ico from icon.png`);
